dataset_name: "SpectralWaste" 
modality: "rgb_hsi"
model_type: "featurefusion" 


rgb_model_config_path: "/home/jon86439/Final_MA/SpectralWaste/configs/RGB/swin_t_rgb_1024.yaml"
rgb_checkpoint_path: "/home/jon86439/Final_MA/SpectralWaste/models/RGB/RGB_1024/swin_t_SpectralWaste_rgb_1024_2_best.pth"

hsi_model_config_path: "/home/jon86439/Final_MA/SpectralWaste/configs/HSI/swin_t_HSI_1.yaml"
hsi_checkpoint_path: "/home/jon86439/Final_MA/SpectralWaste/models/HSI/HSI_1/swin_t_SpectralWaste_hsi_1_run2_best.pth"
hardware:
  gpu: "7"


data_loading:
  num_workers: 16    
  pin_memory: True  
  prefetch_factor: 2
  persistent_workers: True  
  drop_last: True

augmentation:
  enable: True
  rgb_normalization:
    enable: True
    method: "imagenet"
  hsi_normalization:
    enable: True
    method: "standardize"
  pca_transform:
    enable: False
    sovgol: False
    pca_path: ""
  pad_channels:
    enable: False
    pad_channels_to: 225
  resize_rgb: 
    enable: True
    size: 1024 
  resize_hsi: 
    enable: True
    size: 256 
  random_rotate:
    enable: True
    degrees: [-5, 5] 
  random_scale:
    enable: True
    scale_limit: [0.8, 1.3] 
  random_crop_rgb:
    enable: True
    size: 1024
  random_crop_hsi:
    enable: True
    size: 256
  random_flip:
    enable: True
    p_horizontal: 0.5 
    p_vertical: 0.5
  rgb_color_jitter:
    enable: True
    p: 0.8
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.03




fusion:
  fusion_stages: [0, 1, 2, 3]  # Which backbone stages to apply cross-attention
  num_cross_attention_layers: 1  # Number of cross-attention layers per stage


head:
  decoder_channels: [256, 128, 64]
  dropout: 0.1

training:
  random_seed: 41 # Random seed for reproducibility

  batch_size: 2
  val_batch_size: 2
  epochs: 1000
  warmup_epochs: 5
  learning_rate: 1.0e-4
  lr_factors:
    head: 1.0                    
    backbone_pretrained: 0.1    
    backbone_random: 1.0 

  weight_decay: 0.01
  gradient_accumulation_steps: 4
  clip_grad_norm: 0 # Max norm for gradient clipping (0 or null to disable)
  amp: True # Enable Automatic Mixed Precision


  lr_scheduler:
    type: "poly" # "poly", "cosine"
    params:
      power: 0.9
      # For 'cosine'
      #min_lr: 1.0e-6

  loss:
    type: "ce_dice" # "ce", "dice", "focal", "ce_dice"
    ce_weight: 0.5
    dice_weight: 1.5
    focal_gamma: 2.0
    weighting:
      strategy: "frequency" # "none", "custom", "frequency", "square_root"
      # custom_weights: [0.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.0] # Example, adjust to num_classes if strategy is "custom"

  checkpoint_dir: "./models/checkpoints/SpectralWaste/BCAF_RGB_1024_HSI_1_run2" 
  model_dir: "./models/final"         
  model_name: "SpectralWaste_BCAF_RGB_1024_HSI_1_run2" 
  save_checkpoint_interval: 1000 


wandb:
  enable: True
  project: "SpectralWaste" 
  run_name: "BCAF_RGB_1024_HSI_1_run2"


visualization: #for Wandb
  max_images: 4
  log_interval: 1000